import { StyleSheet, Dimensions } from "react-native";
import { BOARD_COLORS, CARD_COLORS } from "../constants/colors";

const { width, height } = Dimensions.get("window");

export const gameStyles = StyleSheet.create({
  table: {
    position: "absolute",
    top: height * 0.25,
    left: width * 0.05,
    width: width * 0.9,
    height: width * 0.9,
    borderRadius: width * 0.5,
    backgroundColor: "#E8D8C9",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  discard: {
    position: "absolute",
    zIndex: 10,
  },
  colorIndicator: {
    position: "absolute",
    padding: 10,
    width: 50,
    height: 80,
    borderRadius: 5,
    marginTop: 7.5,
  },
  playerName: {
    fontWeight: "bold",
    color: BOARD_COLORS.text,
    fontSize: 14,
  },
  otherCards: {
    marginVertical: 5,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  hiddenCard: {
    width: 30,
    height: 45,
    backgroundColor: "#333",
    borderRadius: 5,
    marginHorizontal: 2,
    marginVertical: 2,
  },
  moreCards: {
    fontSize: 12,
    color: BOARD_COLORS.text,
    marginLeft: 5,
  },
  cardCount: {
    fontSize: 12,
    fontWeight: "bold",
    color: BOARD_COLORS.text,
  },
  playerArea: {
    position: "absolute",
    bottom: 50,
    left: 20,
    right: 20,
  },
  yourCards: {
    fontWeight: "bold",
    color: BOARD_COLORS.text,
    marginBottom: 10,
    textAlign: "center",
    fontSize: 18,
  },
  hand: {
    flexDirection: "row",
    paddingBottom: 10,
  },
  card: {
    width: 65,
    height: 90,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 7,
    elevation: 5,
  },
  cardText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    lineHeight: 24,
  },
  controls: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  controlButton: {
    backgroundColor: BOARD_COLORS.accent,
    padding: 15,
    borderRadius: 10,
    flex: 1,
    marginHorizontal: 5,
    marginBottom: 25,
  },
  controlButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  funoButton: {
    backgroundColor: "#FF5252",
    padding: 15,
    borderRadius: 10,
    marginHorizontal: 5,
    marginBottom: 25,
  },
  funoButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  codeContainer: {
    position: "absolute",
    bottom: 80,
    left: 20,
    right: 20,
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    elevation: 3,
  },
  codePrompt: {
    color: BOARD_COLORS.text,
    marginBottom: 10,
    textAlign: "center",
  },
  passwordInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    paddingLeft: 10,
    paddingTop: 5,
    color: "black",
  },
  eyeIcon: {
    right: 10,
  },
  eyeIconImage: {
    width: 22,
    height: 22,
    tintColor: BOARD_COLORS.text,
  },
  currentColorButton: {
    position: "absolute",
    bottom: 700,
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    elevation: 11,
    right: 20,
  },
  currentColorText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  lastActionContainer: {
    position: "absolute",
    top: height * 0.06,
    width: width * 0.3,
    left: width * 0.38,
    alignSelf: "center",
    backgroundColor: "white",
    padding: 5,
    borderRadius: 10,
    zIndex: 100,
    alignItems: "center",
    elevation: 7,
  },
  lastActionText: {
    fontSize: 14,
    fontWeight: "bold",
    color: BOARD_COLORS.text,
    marginBottom: 5,
  },
  lastActionCard: {
    width: 50,
    height: 70,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 5,
  },
  lastActionCardText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  funoContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 110,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    elevation: 10,
  },
  funoMessage: {
    backgroundColor: "rgb(255, 191, 53)",
    padding: 10,
    borderRadius: 10,
  },
  funoText: {
    color: "white",
    fontSize: 48,
    fontWeight: "bold",
    textAlign: "center",
  },
});
